# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Whiteboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Whiteboard-Framework
  pod 'YYModel', '~> 1.0.4'
  pod 'dsBridge', '~> 3.0.2'
end
