#use_frameworks!

platform :ios, '11.0'
project 'Whiteboard.xcodeproj'

target 'Whiteboard_Example' do
  pod 'Whiteboard', :path => '../'
  pod 'Whiteboard/fpa', :path => '../'
  pod 'Masonry'
  pod 'NETURLSchemeHandler'
  pod 'SSZipArchive'
  
  target 'Whiteboard_Tests' do
    inherit! :search_paths
  end
end
