use_frameworks!

platform :ios, '9.0'

target 'Whiteboard_Example' do
  pod 'Whiteboard', :path => '../'
  pod 'Masonry'
  pod 'NETURLSchemeHandler'
  pod 'SSZipArchive'
  
  target 'Whiteboard_Tests' do
    inherit! :search_paths

    
  end
end
