#use_frameworks!
project 'Whiteboard.xcodeproj'

platform :ios, '10.0'

target 'Whiteboard_Example' do
  pod 'Whiteboard', :path => '../'
  pod 'Masonry'
  pod 'NETURLSchemeHandler'
  pod 'SSZipArchive'
  
  target 'Whiteboard_Tests' do
    inherit! :search_paths

    
  end
end
