#!/bin/bash

BASEDIR=$(cd $(dirname "$0"); pwd -P)
set -exo pipefail
cd $BASEDIR

# 更新本地White-bridge build
cd ../Whiteboard-bridge
yarn
yarn build
cd $BASEDIR

# 设置 white-sdk web 资源的目标
export TargetPath=${1-"./Whiteboard/Resource"}
export SourcePath=${2-"../whiteboard-bridge/build"}

# 删除并创建文件目录
rm -rf $TargetPath
mkdir -p $TargetPath
# 从 bridge 复制构建好的 web 资源
cp -r $SourcePath/* $TargetPath/

# 清理 build 文件，否则在 .boundle 里的静态资源文件无法更新
rm -rf ~/Library/Developer/Xcode/DerivedData/WhiteSDKPrivate-*/Build/Products/

cd $BASEDIR/Example
pod install

# 更新与 bridge 的关联
cd $BASEDIR
rabbit update