name: bridge-check
on:
  push:
    branches: [ master ]
    paths: 
      - "carrot.yml"
      - "carrot.yaml"
  pull_request:
    branches: [ master ]
    paths: 
      - "carrot.yml"
      - "carrot.yaml"
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install rabbit-tools -g
      - run: rabbit clone
